name: OpenHands Agent Issue Resolver

on:
  issues:
    types: [labeled]

jobs:
  resolve:
    if: contains(github.event.label.name, 'fix-me')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup OpenHands e2b
        run: pip install "e2b>=0.17.1,<0.18.0"

      - name: Setup OpenHands Resolver
        run: pip install openhands-ai openhands-resolver --no-deps

      - name: Run OpenHands Agent via OpenRouter
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          LLM_MODEL: "openrouter/google/gemma-3-27b-it:free"
        run: |
          export OPENAI_API_KEY=$OPENROUTER_API_KEY
          export OPENAI_BASE_URL="https://openrouter.ai/api/v1"
          openhands-resolver-run \
            --issue-number="${{ github.event.issue.number }}" \
            --target-branch="agent-fixes"
